# Generated by Django 6.0.3 on 2026-03-04 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_cores', models.PositiveIntegerField(default=10)),
                ('ram_mb', models.PositiveIntegerField(default=20480)),
                ('disk_gb', models.PositiveIntegerField(default=500)),
                ('vm_count', models.PositiveIntegerField(default=5)),
                ('public_ip_count', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='tenants.project')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota', to='tenants.tenant')),
            ],
            options={
                'db_table': 'quotas',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', True), ('tenant__isnull', False)), models.Q(('project__isnull', False), ('tenant__isnull', True)), _connector='OR'), name='quota_tenant_xor_project')],
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_cpu_cores', models.PositiveIntegerField(default=0)),
                ('used_ram_mb', models.PositiveIntegerField(default=0)),
                ('used_disk_gb', models.PositiveIntegerField(default=0)),
                ('used_vm_count', models.PositiveIntegerField(default=0)),
                ('used_public_ips', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='tenants.project')),
                ('tenant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='tenants.tenant')),
            ],
            options={
                'db_table': 'usage_counters',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('project__isnull', True), ('tenant__isnull', False)), models.Q(('project__isnull', False), ('tenant__isnull', True)), _connector='OR'), name='usage_tenant_xor_project')],
            },
        ),
    ]
