# Generated by Django 6.0.3 on 2026-03-04 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('size_gb', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('in-use', 'Используется'), ('error', 'Ошибка'), ('creating', 'Создаётся'), ('deleting', 'Удаляется')], default='creating', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disks',
            },
        ),
        migrations.CreateModel(
            name='Firewall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firewalls',
            },
        ),
        migrations.CreateModel(
            name='FirewallBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firewall_bindings',
            },
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ingress', 'Входящий'), ('egress', 'Исходящий')], max_length=8)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP'), ('any', 'Любой')], default='tcp', max_length=8)),
                ('port_range', models.CharField(blank=True, max_length=32, null=True)),
                ('remote_cidr', models.CharField(default='0.0.0.0/0', max_length=18)),
                ('action', models.CharField(choices=[('allow', 'Разрешить'), ('deny', 'Запретить')], default='allow', max_length=8)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'firewall_rules',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='HypervisorAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('kind', models.CharField(choices=[('proxmox', 'Proxmox VE'), ('mock', 'Mock (тестовый)')], default='mock', max_length=16)),
                ('endpoint', models.CharField(blank=True, max_length=256)),
                ('token', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hypervisor_accounts',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cidr', models.CharField(blank=True, max_length=18)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'networks',
            },
        ),
        migrations.CreateModel(
            name='VirtualMachine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('vcpu', models.PositiveSmallIntegerField(default=2)),
                ('ram_mb', models.PositiveIntegerField(default=2048)),
                ('power_state', models.CharField(choices=[('stopped', 'Остановлена'), ('running', 'Работает'), ('suspended', 'Приостановлена'), ('creating', 'Создаётся'), ('provisioning', 'Подготовка'), ('error', 'Ошибка'), ('deleting', 'Удаляется')], default='creating', max_length=16)),
                ('image_ref', models.CharField(blank=True, max_length=128)),
                ('hypervisor_vm_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vms',
            },
        ),
        migrations.CreateModel(
            name='VMNetworkAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vm_network_attachments',
            },
        ),
    ]
