# Generated by Django 6.0.3 on 2026-03-04 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='tenants.project'),
        ),
        migrations.AddField(
            model_name='firewall',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewalls', to='tenants.project'),
        ),
        migrations.AddField(
            model_name='firewallbinding',
            name='firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='compute.firewall'),
        ),
        migrations.AddField(
            model_name='firewallrule',
            name='firewall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='compute.firewall'),
        ),
        migrations.AddField(
            model_name='network',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='tenants.project'),
        ),
        migrations.AddField(
            model_name='firewallbinding',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_bindings', to='compute.network'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='hypervisor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compute.hypervisoraccount'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='primary_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='compute.network'),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vms', to='tenants.project'),
        ),
        migrations.AddField(
            model_name='firewallbinding',
            name='vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firewall_bindings', to='compute.virtualmachine'),
        ),
        migrations.AddField(
            model_name='disk',
            name='attached_vm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disks', to='compute.virtualmachine'),
        ),
        migrations.AddField(
            model_name='vmnetworkattachment',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_attachments', to='compute.network'),
        ),
        migrations.AddField(
            model_name='vmnetworkattachment',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_attachments', to='compute.virtualmachine'),
        ),
        migrations.AlterUniqueTogether(
            name='firewall',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='network',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='virtualmachine',
            unique_together={('project', 'name')},
        ),
        migrations.AddConstraint(
            model_name='firewallbinding',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('network__isnull', True), ('vm__isnull', False)), models.Q(('network__isnull', False), ('vm__isnull', True)), _connector='OR'), name='fw_binding_vm_xor_network'),
        ),
        migrations.AlterUniqueTogether(
            name='disk',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vmnetworkattachment',
            unique_together={('vm', 'network')},
        ),
    ]
