# Generated by Django 6.0.3 on 2026-03-04 23:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compute', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('vcpu', models.PositiveSmallIntegerField()),
                ('ram_mb', models.PositiveIntegerField()),
                ('disk_gb', models.PositiveIntegerField()),
                ('price_label', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'flavors',
                'ordering': ['vcpu', 'ram_mb'],
            },
        ),
        migrations.CreateModel(
            name='OSTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('min_disk_gb', models.PositiveIntegerField(default=10)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'os_templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='compute_node',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='disk_gb',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='flavor',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='ssh_key',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ComputeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance'), ('draining', 'Draining')], default='online', max_length=16)),
                ('cpu_total', models.PositiveIntegerField(default=64)),
                ('cpu_used', models.PositiveIntegerField(default=0)),
                ('ram_total_mb', models.PositiveIntegerField(default=131072)),
                ('ram_used_mb', models.PositiveIntegerField(default=0)),
                ('disk_total_gb', models.PositiveIntegerField(default=2000)),
                ('disk_used_gb', models.PositiveIntegerField(default=0)),
                ('vm_count', models.PositiveIntegerField(default=0)),
                ('uptime', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hypervisor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='compute.hypervisoraccount')),
            ],
            options={
                'db_table': 'compute_nodes',
            },
        ),
    ]
