# Generated by Django 6.0.3 on 2026-03-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='task',
            name='external_node',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
