# Generated by Django 6.0.3 on 2026-03-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        ('iam', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='created_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='tenants.project'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='created_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='provision_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to='audit.task'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
